parameters:
#    qiiss_user.example.class: Qiiss\UserBundle\Example

services:
#    qiiss_user.example:
#        class: %qiiss_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
