# src/Qiiss/UserBundle/Resources/config/services.yml
parameters:
    vendor_security.authentication_handler: Qiiss\UserBundle\Handler\AjaxHandler
services:
    qiiss_user.registration.form.type:
        class: Qiiss\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: qiiss_user_registration }
    qiiss_user.change_password.form.type:
        class: Qiiss\UserBundle\Form\Type\ChangePasswordFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: qiiss_user_change_password }
    authentication_handler:
        class:  %vendor_security.authentication_handler%
        arguments:  [@router]
