qiiss_profile_propose_date:
    pattern:  /propose-date/{profileid}
    defaults: { _controller: QiissProfileBundle:Profile:proposeDate }

qiiss_profile:
    pattern:  /profile/{profileid}
    defaults: { _controller: QiissUserBundle:Retrieve:getProfile }

qiiss_profile_view_date:
    pattern:  /date/{dateid}
    defaults: { _controller: QiissProfileBundle:Profile:viewDate }

qiiss_profile_accept_date:
    pattern:  /accept-date/{dateid}
    defaults: { _controller: QiissProfileBundle:Profile:acceptDate }

qiiss_profile_decline_date:
    pattern:  /decline-date/{dateid}
    defaults: { _controller: QiissProfileBundle:Profile:declineDate }

qiiss_profile_ignore_date:
    pattern:  /ignore-date/{dateid}
    defaults: { _controller: QiissProfileBundle:Profile:ignoreDate }

qiiss_profile_send_message:
    pattern:  /message/send/{dateid}
    defaults: { _controller: QiissProfileBundle:Message:sendMessage }

qiiss_profile_get_messages_old:
    pattern: /message/get-old/{dateid}
    defaults: { _controller: QiissProfileBundle:Message:getOldMessages }

qiiss_profile_get_messages_new:
    pattern: /message/get-new/{dateid}
    defaults: { _controller: QiissProfileBundle:Message:getNewMessages }

qiiss_wall_post:
    pattern: /wall-post
    defaults: { _controller: QiissWallBundle:Wall:post }

qiiss_get_wall_posts:
    pattern: /get-wall-post/{userid}
    defaults: { _controller: QiissWallBundle:Wall:getUserWallPosts }

qiiss_like_wall_post:
    pattern: /qool-wall-post/{postid}
    defaults: { _controller: QiissWallBundle:Wall:toggleLikePost }

qiiss_get_single_wall_post:
    pattern: /get-single-wall-post/{postid}
    defaults: { _controller: QiissWallBundle:Wall:getSinglePost }

qiiss_profile_upload:
    pattern:  /upload
    defaults: { _controller: QiissWallBundle:Wall:upload }

qiiss_profile_photos:
    pattern: /photos/{userid}
    defaults: { _controller: QiissWallBundle:Photo:showPhotos }

qiiss_get_photos:
    pattern: /get-photos/{userid}
    defaults: { _controller: QiissWallBundle:Photo:getPhotos }

qiiss_publish_photo:
    pattern: /publish-photo/{photoid}
    defaults: { _controller: QiissWallBundle:Photo:publishPhoto }

qiiss_delete_photo:
    pattern: /delete-photo/{photoid}
    defaults: { _controller: QiissWallBundle:Photo:deletePhoto }

qiiss_like_photo:
    pattern: /qool-photo/{photoid}
    defaults: { _controller: QiissWallBundle:Photo:toggleLikePhoto }

qiiss_set_dp:
    pattern: /set-display-picture/{photoid}
    defaults: { _controller: QiissWallBundle:Photo:setDisplayPicture }

qiiss_predict_interests:
    pattern: /interests/predict
    defaults: { _controller: QiissUserBundle:Interest:predictInterests }

qiiss_set_interests:
    pattern: /interests/set
    defaults: { _controller: QiissUserBundle:Interest:setInterests }

qiiss_profile_search:
    pattern:  /search
    defaults: { _controller: QiissSearchBundle:Search:index}
