qiiss_profile_propose_date:
    pattern:  /propose-date/{profileid}
    defaults: { _controller: QiissProfileBundle:Profile:proposeDate }

qiiss_profile:
    pattern:  /profile/{profileid}
    defaults: { _controller: QiissUserBundle:Retrieve:getProfile }

qiiss_profile_view_date:
    pattern:  /date/{dateid}
    defaults: { _controller: QiissProfileBundle:Profile:viewDate }

qiiss_profile_post:
    pattern:  /wall
    defaults: { _controller: QiissWallBundle:Wall:post }

qiiss_profile_upload:
    pattern:  /upload
    defaults: { _controller: QiissWallBundle:Wall:upload }
