qiiss_profile_propose_date:
    pattern:  /propose-date/{profileid}
    defaults: { _controller: QiissProfileBundle:Profile:proposeDate }

qiiss_profile:
    pattern:  /profile/{profileid}
    defaults: { _controller: QiissUserBundle:Retrieve:getProfile }

qiiss_profile_view_date:
    pattern:  /date/{dateid}
    defaults: { _controller: QiissProfileBundle:Profile:viewDate }

qiiss_profile_post:
    pattern:  /wall
    defaults: { _controller: QiissWallBundle:Wall:post }

qiiss_profile_send_message:
    pattern:  /message/send/{dateid}
    defaults: { _controller: QiissProfileBundle:Message:sendMessage }

qiiss_profile_get_messages_old:
    pattern: /message/get-old/{dateid}
    defaults: { _controller: QiissProfileBundle:Message:getOldMessages }

qiiss_profile_get_messages_new:
    pattern: /message/get-new/{dateid}
    defaults: { _controller: QiissProfileBundle:Message:getNewMessages }