<?php

namespace Qiiss\NotyBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class NotyController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Qiiss\NotyBundle\Controller\NotyController();
        return $instance;
    }
}
