<?php

namespace Qiiss\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RetrieveController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Qiiss\UserBundle\Controller\RetrieveController();
        return $instance;
    }
}
