<?php

namespace Proxies\__CG__\Qiiss\ProfileBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Date extends \Qiiss\ProfileBundle\Entity\Date implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEventDescription($eventDescription)
    {
        $this->__load();
        return parent::setEventDescription($eventDescription);
    }

    public function getEventDescription()
    {
        $this->__load();
        return parent::getEventDescription();
    }

    public function setEventDate($eventDate)
    {
        $this->__load();
        return parent::setEventDate($eventDate);
    }

    public function getEventDate()
    {
        $this->__load();
        return parent::getEventDate();
    }

    public function setEventPlace($eventPlace)
    {
        $this->__load();
        return parent::setEventPlace($eventPlace);
    }

    public function getEventPlace()
    {
        $this->__load();
        return parent::getEventPlace();
    }

    public function setEventMedia($eventMedia)
    {
        $this->__load();
        return parent::setEventMedia($eventMedia);
    }

    public function getEventMedia()
    {
        $this->__load();
        return parent::getEventMedia();
    }

    public function setEventLink($eventLink)
    {
        $this->__load();
        return parent::setEventLink($eventLink);
    }

    public function getEventLink()
    {
        $this->__load();
        return parent::getEventLink();
    }

    public function setEventPrice($eventPrice)
    {
        $this->__load();
        return parent::setEventPrice($eventPrice);
    }

    public function getEventPrice()
    {
        $this->__load();
        return parent::getEventPrice();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'event_description', 'event_date', 'event_place', 'event_media', 'event_link', 'event_price');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}