parameters:
#    qiiss_charity.example.class: Qiiss\CharityBundle\Example

services:
#    qiiss_charity.example:
#        class: %qiiss_charity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
