parameters:
#    qiiss_general.example.class: Qiiss\GeneralBundle\Example

services:
#    qiiss_general.example:
#        class: %qiiss_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
