Qiiss\UserBundle\Entity\User:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: '50'
        email:
            type: string
            length: '200'
        password:
            type: string
            length: '100'
        dob:
            type: datetime
            length: null
    lifecycleCallbacks: {  }
